### ISSUE TITLE
Topics are not getting listed

### ISSUE THREAD

**Issue by rajkaran** [chris-kent/Easy-Forums#2]
When ever I creates a new topic that topic doesn't gets listed; neither in topic nor in forum.

Is there any way to restrict users from creating topics. We want to allow a small group of users to create topics and any one can comment.

**Comment by chris-kent** [comment]
This has been addressed in Version 2.0 of the plugin

**Comment by miksandb** [comment]
I still see this issue in 2.3 and Confluence 5.9.4. The Forum summary is not showing my forums, and the forum is not showing my topics

**Comment by chris-kent** [comment]
Hi Mikael,

I would love to get to the bottom of this issue, can you please do the following for me to help diagnose this problem.

1. Turn on debugging for the plugin. Go to Confluence Admin -> Logging and Profiling
     Add a new entry on the logging for "net.kentcom" "ALL"
2. Refresh the Forum Summary page and also one of the Forum pages
3. Go to the Confluence log file and copy all the lines from the plugin, these will have the following tag in them [net.kentcom.
4. Send the results to my email (see below)
5. If you can also send full screen shots of both your Forum Summary page and one of your Forum pages.

Hopefully this will help me diagnose what is going wrong...

Cheers
Chris
(mr.chris.kent@gmail.com)
